<nav class="navbar navbar-expand-lg navbar-dark  navCustom">
    <div class="container-fluid">
        <h2 class="logo"><span>J</span>ármű<span>L</span>ogisztika</h2>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="/adminhome">Főoldal</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Felhasználók
                    </a>
                    <ul class="dropdown-menu dropCustom" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="useradd">Új felhasználó</a></li>
                        <li><a class="dropdown-item" href="userhand">Felhasználók kezelése</a></li>
                        <li><a class="dropdown-item" href="messsend">Üzenet küldése</a></li>
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Járművek
                    </a>
                    <ul class="dropdown-menu dropCustom" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="caradd">Új jármű</a></li>
                        <li><a class="dropdown-item" href="carhand">Járművek kezelése</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="reshand">Foglalások</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Szervíz
                    </a>
                    <ul class="dropdown-menu dropCustom" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="servicehand?rep=0">Javítandó járművek</a></li>
                        <li><a class="dropdown-item" href="servicehand?rep=1">Javított</a></li>
                        <li><a class="dropdown-item" href="servicehand?rep=2">Teljes lista</a></li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/log">Naplók</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/passw_mod">Jelszómódosítás</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/logout">Kilépés</a>
                </li>
            </ul>
        </div>
    </div>
</nav>