<nav class="navbar navbar-expand-lg navbar-dark  navCustom">
    <div class="container-fluid">
        <h2 class="logo"><span>J</span>ármű<span>L</span>ogisztika</h2>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="home">Főoldal</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="resadd">Járműfoglalás</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="reslist">Foglalásaim</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="serviceadd">Szervízbejelentés</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="messsend">Üzenetküldés</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="passw_mod">Jelszómódosítás</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/logout">Kilépés</a>
                </li>
            </ul>
        </div>
    </div>
</nav>